require 'ox'
require 'dustbag/version'

module Dustbag
  autoload :Accessories, 'dustbag/accessories'
  autoload :Accessory, 'dustbag/accessory'
  autoload :Arguments, 'dustbag/arguments'
  autoload :AvailabilityAttributes, 'dustbag/availability_attributes'
  autoload :BrowseNode, 'dustbag/browse_node'
  autoload :BrowseNodes, 'dustbag/browse_nodes'
  autoload :Common, 'dustbag/common'
  autoload :CustomerReviews, 'dustbag/customer_reviews'
  autoload :Dimension, 'dustbag/dimension'
  autoload :Dimensions, 'dustbag/dimensions'
  autoload :EditorialReview, 'dustbag/editorial_review'
  autoload :EditorialReviews, 'dustbag/editorial_reviews'
  autoload :HttpHeaders, 'dustbag/http_headers'
  autoload :Image, 'dustbag/image'
  autoload :ImageSet, 'dustbag/image_set'
  autoload :ImageSets, 'dustbag/image_sets'
  autoload :Item, 'dustbag/item'
  autoload :ItemAttributes, 'dustbag/item_attributes'
  autoload :ItemLink, 'dustbag/item_link'
  autoload :ItemLinks, 'dustbag/item_links'
  autoload :ItemSearchRequest, 'dustbag/item_search_request'
  autoload :ItemSearchResponse, 'dustbag/item_search_response'
  autoload :Items, 'dustbag/items'
  autoload :Language, 'dustbag/language'
  autoload :Languages, 'dustbag/languages'
  autoload :Offer, 'dustbag/offer'
  autoload :OfferSummary, 'dustbag/offer_summary'
  autoload :Offers, 'dustbag/offers'
  autoload :OperationRequest, 'dustbag/operation_request'
  autoload :Parser, 'dustbag/parser'
  autoload :Price, 'dustbag/price'
  autoload :Request, 'dustbag/request'
  autoload :SimilarProduct, 'dustbag/similar_product'
  autoload :SimilarProducts, 'dustbag/similar_products'
  autoload :SimpleProduct, 'dustbag/simple_product'
  autoload :VariationAttribute, 'dustbag/variation_attribute'
  autoload :VariationAttributes, 'dustbag/variation_attributes'
  autoload :VariationSummary, 'dustbag/variation_summary'
  autoload :Variations, 'dustbag/variations'
end
